import type { TranscriptLine } from "../types";

interface Props {
  lines: TranscriptLine[];
}

function fmtTime(secs: number) {
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
}

const ROLE_STYLES = {
  officer: "bg-blue-600 text-white",
  suspect: "bg-orange-500 text-white",
  witness: "bg-green-500 text-white",
  unknown: "bg-gray-400 text-white",
};

export default function TranscriptPanel({ lines }: Props) {
  const sorted = [...lines].sort((a, b) => a.start_seconds - b.start_seconds);

  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
        <p className="text-sm text-gray-500">
          Transcript generated by Azure Video Indexer via speech-to-text with speaker diarization.
        </p>
        <span className="text-xs text-gray-400">{sorted.length} segments</span>
      </div>

      <div className="divide-y divide-gray-50 max-h-[600px] overflow-y-auto">
        {sorted.map((line, i) => (
          <div
            key={i}
            className={`px-6 py-4 flex gap-4 items-start ${
              i % 2 === 0 ? "bg-white" : "bg-gray-50/50"
            }`}
          >
            {/* Timestamp */}
            <div className="flex-shrink-0 w-12 pt-0.5">
              <span className="font-mono text-xs text-gray-400">{fmtTime(line.start_seconds)}</span>
            </div>

            {/* Speaker label */}
            <div className="flex-shrink-0 w-32">
              <span
                className={`text-xs font-semibold px-2 py-0.5 rounded-full ${
                  ROLE_STYLES[line.speaker_role] ?? ROLE_STYLES.unknown
                }`}
              >
                {line.speaker_role === "officer"
                  ? "Officer"
                  : line.speaker_role === "suspect"
                  ? "Subject"
                  : line.speaker_role}
              </span>
              <p className="text-xs text-gray-400 mt-0.5 truncate" title={line.speaker}>
                {line.speaker.split(" ").slice(0, 2).join(" ")}
              </p>
            </div>

            {/* Text */}
            <div className="flex-1">
              <p className="text-sm text-gray-800">{line.text}</p>
              {line.confidence < 0.9 && (
                <p className="text-xs text-amber-600 mt-0.5">
                  Low confidence ({Math.round(line.confidence * 100)}%) — verify manually
                </p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
